[tool.ruff]
# # select で指定するとチェックの対象のルールとなる
# select = ["I", "N"] # Iはisort, Nはpep8-naming
# # ignore で指定するとチェックの対象外のルールとなる
# ignore = ["E", "F"] # Eはpycodestyle, Fはpyflakes
select = ["E", "F", "I"]
unfixable = ["F401", "F841"] # F401はimportが未使用, F841は変数が未使用 それぞれの修正は行わない
line-length = 120
